### **Collaborative Filtering (협업 필터링 : 사용자 리뷰 기반)**

나 : Up, 주토피아

다른 사람 : Up, 주토피아, 인사이드 아웃

**참고 자료**   
https://surprise.readthedocs.io/en/stable/getting_started.html   
https://surprise.readthedocs.io/en/stable/reader.html

In [1]:
!pip install scikit-surprise

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting scikit-surprise
  Downloading scikit-surprise-1.1.1.tar.gz (11.8 MB)
     |████████████████████████████████| 11.8 MB 3.0 MB/s
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-surprise) (1.1.0)
Requirement already satisfied: numpy>=1.11.2 in /usr/local/lib/python3.7/dist-packages (from scikit-surprise) (1.21.6)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-surprise) (1.7.3)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.7/dist-packages (from scikit-surprise) (1.15.0)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (setup.py) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.1-cp37-cp37m-linux_x86_64.whl size=1633703 sha256=6b0866d9e8126f31bc596e15e8920789e400347d370053f0812b15b1e6bbac2f
  Stored in directory: /root/.cache/pip/wheels/76/44/74/b498c42be47b2406bd27994e16c5188e337c657025ab400c1c
Successfully built scikit-surprise
Installing collected packages: scikit-surprise
Successfully installed scikit-surprise-1.1.1

In [3]:
import surprise
surprise.__version__

'1.1.1'

In [4]:
import pandas as pd
from surprise import Reader, Dataset, SVD
from surprise.model_selection import cross_validate

In [7]:
ratings = pd.read_csv('ratings_small.csv')
ratings.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [8]:
ratings['rating'].min()

0.5

In [9]:
ratings['rating'].max()

5.0

In [10]:
reader = Reader(rating_scale=(0.5, 5))

In [11]:
data = Dataset.load_from_df(ratings[['userId', 'movieId', 'rating']], reader=reader)

In [12]:
svd = SVD(random_state=0)

In [13]:
cross_validate(svd, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)   # 교차 검증 (5세트)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std
RMSE (testset)    0.8864  0.9057  0.8964  0.8990  0.8992  0.8973  0.0063
MAE (testset)     0.6807  0.6989  0.6881  0.6935  0.6931  0.6909  0.0061
Fit time          9.02    8.52    5.15    5.12    6.05    6.77    1.67
Test time         0.26    0.18    0.24    0.18    0.14    0.20    0.04

{'fit_time': (9.017058849334717,
  8.518498659133911,
  5.1492249965667725,
  5.116325855255127,
  6.0507683753967285),
 'test_mae': array([0.68070274, 0.69885388, 0.68810504, 0.69350224, 0.69309093]),
 'test_rmse': array([0.88637811, 0.9056937 , 0.89640848, 0.89903166, 0.89921889]),
 'test_time': (0.25867247581481934,
  0.18184590339660645,
  0.24417400360107422,
  0.17798662185668945,
  0.1423814296722412)}

In [14]:
trainset = data.build_full_trainset()
svd.fit(trainset)

In [16]:
ratings[ratings['userId'] == 1]

    userId  movieId  rating   timestamp
0        1       31     2.5  1260759144
1        1     1029     3.0  1260759179
2        1     1061     3.0  1260759182
3        1     1129     2.0  1260759185
4        1     1172     4.0  1260759205
5        1     1263     2.0  1260759151
6        1     1287     2.0  1260759187
7        1     1293     2.0  1260759148
8        1     1339     3.5  1260759125
9        1     1343     2.0  1260759131
10       1     1371     2.5  1260759135
11       1     1405     1.0  1260759203
12       1     1953     4.0  1260759191
13       1     2105     4.0  1260759139
14       1     2150     3.0  1260759194
15       1     2193     2.0  1260759198
16       1     2294     2.0  1260759108
17       1     2455     2.5  1260759113
18       1     2968     1.0  1260759200
19       1     3671     3.0  1260759117

In [17]:
svd.predict(1, 302)

Prediction(uid=1, iid=302, r_ui=None, est=2.7142061734434044, details={'was_impossible': False})

In [18]:
svd.predict(1, 1029)    #UserId 1번인 사람이 movieId 1029 인 영하에 대하여 실제 평가 3점일 때, 예측 평가 점수?

Prediction(uid=1, iid=1029, r_ui=None, est=2.8814455446761933, details={'was_impossible': False})

In [19]:
ratings[ratings['userId'] == 100]

       userId  movieId  rating  timestamp
15273     100        1     4.0  854193977
15274     100        3     4.0  854194024
15275     100        6     3.0  854194023
15276     100        7     3.0  854194024
15277     100       25     4.0  854193977
15278     100       32     5.0  854193977
15279     100       52     3.0  854194056
15280     100       62     3.0  854193977
15281     100       86     3.0  854194208
15282     100       88     2.0  854194208
15283     100       95     3.0  854193977
15284     100      135     3.0  854194086
15285     100      141     3.0  854193977
15286     100      608     4.0  854194024
15287     100      648     3.0  854193977
15288     100      661     3.0  854194086
15289     100      708     3.0  854194056
15290     100      733     3.0  854194024
15291     100      736     3.0  854193977
15292     100      745     4.0  854194208
15293     100      780     3.0  854193977
15294     100      786     3.0  854194056
15295     100      802     4.0  854194111
15296     100     1073     5.0  854194056
15297     100     1356     4.0  854194086

In [23]:
svd.predict(100, 1029)

Prediction(uid=100, iid=1029, r_ui=None, est=3.7705476478414846, details={'was_impossible': False})